name: dialogix
description: >
  Discover the art of meaningful conversations with Dialogix, a dynamic social platform crafted for engaging discussions and community building. Seamlessly navigate threads, share insights, and connect with like-minded individuals. Dive into a world where your voice matters, and ideas take center stage. Elevate your online dialogue experience with Dialogix – where conversation meets community, and connection is at the core.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"


dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # UI and Styling
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  flutter_screenutil: ^5.9.0
  gap: ^3.0.1
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  dotted_border: ^2.1.0
  gallery_picker: ^0.4.8
  detectable_text_field: ^3.0.2

  # Animation
  animate_do: ^3.1.2

  # Firebase Services
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  google_sign_in: ^6.2.1
  firebase_ui_firestore: ^1.5.15
  firebase_dynamic_links: ^5.4.8

  # State Management
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  riverpod_generator: ^2.3.9

  # JSON Serialization
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  # Functional Programming
  fpdart: ^1.1.0

  # Navigation
  routemaster: ^1.0.1

  # Other
  uuid: ^4.2.2
  file_picker: ^6.1.1
  shared_preferences: ^2.2.2
  any_link_preview: ^3.0.1
  intl: ^0.18.1

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Linting and Code Quality
  flutter_lints: ^3.0.1
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  build_runner: ^2.4.7

  # Native
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8

# Flutter launcher icons config
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/native/dialogix_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 2

flutter:
  # Design
  uses-material-design: true

  # Assets
  assets:
    - assets/images/google.png
    - assets/images/loginEmote.png
    - assets/images/logo.png
    - assets/images/awards/
    - assets/icons/
    - assets/images/native/

  # Fonts
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Black.ttf
          weight: 900
        - asset: assets/fonts/Gilroy-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Gilroy-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Gilroy-Heavy.ttf
          weight: 900
        - asset: assets/fonts/Gilroy-HeavyItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Gilroy-Thin.ttf
          weight: 100
        - asset: assets/fonts/Gilroy-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Gilroy-UltraLight.ttf
          weight: 200
        - asset: assets/fonts/Gilroy-UltraLightItalic.ttf
          weight: 200
          style: italic
